print("Welcome to MAD-LIB")
print("Please awnswer the following questions")
print("")

adjective1 = input("Enter an adjective e.g Small/Broken/Smelly >>> ")
nationality1 = input("Enter a nationality >>> ")
person1 = input("Enter a name >>> ")
age1 = int(input("Enter an age >>>"))
vegetable1 = input("Enter a vegetable >>> ")
adjective2 = input("Enter an adjective e.g Small/Broken/Smelly >>> ")
nationality2 = input("Enter a nationality >>> ")
person2 = input("Enter a name >>> ")
age2 = int(input("Enter an age >>>"))
vegetable2 = input("Enter a vegetable >>> ")

print("Vegetables where first discovered by a",adjective1,nationality1,"man named",person1)
print(person1,"discovered the vegetable at",age1,"and the first vegetable he discovered was a",vegetable1)
print("but",person2,"a",adjective2,"man,"" wanted to sabotage his vegetable fame.",person2,"created a fake vegetable called",vegetable2,"to make people believe he found the first vegetable")
print(person2,"was only",age2,"when he decided to sabotage",person1,"and ruin",person1,"lifelong dream of being vegetable famous")

